services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_ENDPOINT=http://backend:80/generate_ad/  # Update with the correct endpoint